version: '3.2'

services:
  node:
    build:
      context: ./docker/custom-images/node
      dockerfile: Dockerfile
    ports: 
        - 3000:3000
    volumes:
        - ./:/home/node/repository
        - ./docker/config/ssh/id_rsa:/home/node/.ssh/id_rsa
        - ./docker/config/ssh/id_rsa.pub:/home/node/.ssh/id_rsa.pub
        - ./docker/config/ssh/known_hosts:/home/node/.ssh/known_hosts
        - ./docker/config/git/.gitconfig:/home/node/.gitconfig